[package]
name = "pongos"
version = "0.1.0"
edition = "2024"

[dependencies]
bootloader = "0.9.0"
lazy_static = {version = "1.5.0", features = ["spin_no_std"]}
spin = "0.10.0"
usbd-serial = "0.2.2"
x86_64 = "0.15.2"
